services:
  postgres:
    image: postgres:15-alpine
    container_name: hyrion-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - hyrion-db-data:/var/lib/postgresql/data

volumes:
  hyrion-db-data: